// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fkicyazzrdmvgqfzrczz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZraWN5YXp6cmRtdmdxZnpyY3p6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzOTMwNDEsImV4cCI6MjA1Nzk2OTA0MX0.rr7_olhYNgPKHgX2uMtdUqYmvtpiRxGcRvc7igbJpWQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);